### ISSUE TITLE
How to intergrate InterFace into CosFace

### ISSUE THREAD

**Issue by Noobzm** [iamsangmeng/InterFace#1]
Hello, have you tried integrating InterFace into CosFace? if yes, how did it work and can you provide the code snippet? 
(In my dataset, CosFace is able to converge better than ArcFace, so I wonder if InterFace can improve my loss)

Thanks in advanced!

**Comment by Meng-Sang** [comment]
Sorry, we didn't integrate InterFace to CosFace. if you are interested in our approach, you can try this work.
